# Generated by Django 3.1.4 on 2020-12-29 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is a description of product.'),
            preserve_default=False,
        ),
    ]
